- name: Install
  become: true
  dnf:
    name: alacritty
    state: latest
  when: ansible_distribution == 'Fedora'

- block:
  - name: Install dependencies
    apt:
      pkg:
        - cmake
        - pkg-config
        - libfreetype6-dev
        - libfontconfig1-dev
        - libxcb-xfixes0-dev
        - libxkbcommon-dev
        - python3
  - name: Install alacritty
    shell: cargo install alacritty

  - name: Create oh-my-zsh functions directory
    file:
      path: ~/.oh-my-zsh/functions
      state: directory

  - name: Add zsh completion
    shell: |
      curl -s https://api.github.com/repos/alacritty/alacritty/releases/latest \
      | jq -r '.assets[] | select(.name == "_alacritty") | .browser_download_url' \
      | xargs wget -P ~/.oh-my-zsh/functions

  - name: Create man1 directory
    become: true
    file:
      path: /usr/local/share/man/man1
      state: directory

  - name: Download alacritty man pages
    shell: |
      curl -s https://api.github.com/repos/alacritty/alacritty/releases/latest \
      | jq -r '.assets[] | select(.name == "alacritty.1.gz") | .browser_download_url' \
      | xargs wget -P /tmp

  - name: Install alacritty man pages
    become: true
    shell: mv /tmp/alacritty.1.gz /usr/local/share/man/man1/alacritty.1.gz

  - name: Create local pixmaps directory
    become: true
    file:
      path: /usr/local/share/pixmaps
      state: directory

  - name: Create local applications directory
    become: true
    file:
      path: /usr/local/share/applications
      state: directory

  - name: Download alacrity icon
    shell: |
      curl -s https://api.github.com/repos/alacritty/alacritty/releases/latest \
      | jq -r '.assets[] | select(.name == "Alacritty.svg") | .browser_download_url' \
      | xargs wget -P /tmp

  - name: Download alacrity .desktop
    shell: |
      curl -s https://api.github.com/repos/alacritty/alacritty/releases/latest \
      | jq -r '.assets[] | select(.name == "Alacritty.desktop") | .browser_download_url' \
      | xargs wget -P /tmp

  - name: Move .desktop files
    become: true
    shell: |
      mv /tmp/Alacritty.svg /usr/local/share/pixmaps
      mv /tmp/Alacritty.desktop /usr/local/share/applications

  when: ansible_distribution == 'Debian'

- name: Link alacritty config
  file:
    src: ~/dotfiles/alacritty
    dest: ~/.config/alacritty
    state: link
