- when: ansible_distribution == 'Debian'
  block: 
    - name: Download Brave GPG key
      become: true
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg

    - name: Add Brave repository
      become: true
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/brave-browser-release.list
        line: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        create: yes

    - name: Update apt
      become: true
      command: nala update

    - name: Install Brave package
      become: true
      command: nala install -y brave-browser