- name: Install Flatpak
  become: true
  package:
    name: flatpak
    state: present

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  flatpak:
    name: "{{ item }}"
  with_items:
    - com.bitwarden.desktop
    - org.gnome.Calculator

- name: Install flatpak apps (Debian)
  flatpak:
    name: com.getpostman.Postman
  when: ansible_distribution == 'Debian'
