- name: Install Flatpak
  package:
    name: flatpak
    state: present

- name: Add FlatHub repository
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  flatpak:
    name:
      - com.bitwarden.desktop

- name: Install flatpak apps (Debian)
  flatpak:
    name:
      - com.getpostman.Postman
  when: ansible_distribution == 'Debian'
