- name: Create fonts directory for Nerd fonts
  become: true
  file:
    path: /usr/local/share/fonts/NerdFonts
    state: directory

- name: Download font
  shell: |
    curl -s https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest \
    | jq -r '.assets[] | select(.name == "SourceCodePro.zip") | .browser_download_url' \
    | xargs wget -P /tmp

- name: Extract font zip
  become: true
  ansible.builtin.unarchive:
    src: /tmp/SourceCodePro.zip
    dest: /usr/local/share/fonts/NerdFonts

- name: Update font cache
  become: true
  command: fc-cache -f
