- when: ansible_distribution == 'Debian'
  block:
  - name: Check if neovim is already installed
    command: which nvim
    ignore_errors: true
    changed_when: false
    register: check_neovim_installed

  - when: check_neovim_installed.rc != 0
    block:
      - name: Download Neovim appimage
        get_url:
          url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
          dest: /tmp/nvim.appimage
          mode: '0755'

      - name: Unpack Neovim appimage
        command: ./nvim.appimage --appimage-extract
        args:
          chdir: /tmp

      - name: Install neovim files
        become: true
        copy:
          remote_src: true
          src: /tmp/squashfs-root/usr/
          dest: /usr
          mode: preserve

      - name: Clean neovim tmp files
        file:
          path: "/tmp/{{ item }}"
          state: absent
        with_items:
          - squashfs-root
          - nvim.appimage


- when: ansible_distribution == 'Fedora'
  name: Install neovim (Fedora)
  become: true
  dnf:
    name: neovim


- name: Link .config/nvim
  file:
    src: ~/dotfiles/neovim/nvim
    dest: ~/.config/nvim
    state: link

- name: Link .ideavimrc
  file:
    src: ~/dotfiles/neovim/ideavimrc.vim
    dest: ~/.ideavimrc
    state: link

- name: Install Packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Install Plugins
  command: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

- name: Remove vim
  become: true
  package:
    name:
      - vim
      - vim-common
      - vim-tiny
      - vim-runtime
    state: absent

- name: Create vim aliases
  become: true
  file:
    src: /usr/bin/nvim
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - vi
    - vim
