- block:  # we install neovim through packages on fedora
  - name: Download Neovim appimage
    get_url:
      url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
      dest: /tmp/nvim.appimage
      mode: '0755'
  
  - name: Unpack Neovim appimage
    command: ./nvim.appimage --appimage-extract

  - name: Unpack Neovim appimage
    become: true
    copy:
      src: /tmp/squashfs-root/usr
      dest: /
      directory_mode: true

  when: ansible_distribution == 'Debian'

- name: Install neovim (Fedora)
  become: true
  dnf:
    name: neovim
  when: ansible_distribution == 'Fedora'

- name: Link .config/nvim
  file:
    src: ~/dotfiles/neovim/nvim
    dest: ~/.config/nvim
    state: link

- name: Link .ideavimrc
  file:
    src: ~/dotfiles/neovim/ideavimrc.vim
    dest: ~/.ideavimrc
    state: link

- name: Install VimPlug
  shell: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Install Plugins
  shell: nvim +PlugInstall +qall
