- block:  # we install neovim through packages on fedora
  - name: Download Neovim appimage
    get_url:
      url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
      dest: /tmp/nvim.appimage
      mode: '0755'
  
  - name: Unpack Neovim appimage
    command: ./nvim.appimage --appimage-extract
    args:
      chdir: /tmp

  - name: Install neovim files
    become: true
    copy:
      remote_src: true
      src: /tmp/squashfs-root/usr/
      dest: /usr
      mode: preserve

  - name: Clean neovim tmp files
    file:
      path: "/tmp/{{ item }}"
      state: absent
    with_items:
      - squashfs-root
      - nvim.appimage

  when: ansible_distribution == 'Debian'

- name: Install neovim (Fedora)
  become: true
  dnf:
    name: neovim
  when: ansible_distribution == 'Fedora'

- name: Link .config/nvim
  file:
    src: ~/dotfiles/neovim/nvim
    dest: ~/.config/nvim
    state: link

- name: Link .ideavimrc
  file:
    src: ~/dotfiles/neovim/ideavimrc.vim
    dest: ~/.ideavimrc
    state: link

- name: Install Packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Install Plugins
  command: nvim +PackerCompile +PackerInstall +qall

- name: Remove vim
  become: true
  package:
    name: vim
    state: absent
  
- name: Create vim aliases
  become: true
  file:
    src: /usr/bin/nvim
    dest: "/usr/bin/{{ item }}"
    state: link
  with_items:
    - vi
    - vim
  
