- block:  # we install neovim through packages on fedora
  - name: Download .deb
    shell: |
      curl -s https://api.github.com/repos/neovim/neovim/releases/latest \
      | jq -r '.assets[] | select(.name == "nvim-linux64.deb") | .browser_download_url' \
      | xargs wget -O /tmp/nvim.deb

  - name: Install
    become: true
    apt:
      deb: /tmp/nvim.deb

  - name: Clean .deb
    shell: rm /tmp/nvim.deb
  when: ansible_distribution == 'Debian'

- name: Install neovim (Fedora)
  become: true
  dnf:
    name: neovim
  when: ansible_distribution == 'Fedora'

- name: Link .config/nvim
  file:
    src: ~/dotfiles/neovim/nvim
    dest: ~/.config/nvim
    state: link

- name: Link .ideavimrc
  file:
    src: ~/dotfiles/neovim/ideavimrc.vim
    dest: ~/.ideavimrc
    state: link

- name: Install VimPlug
  shell: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Install Plugins
  shell: nvim +PlugInstall +qall
