- set_fact:
    common_packages:
      - xclip
      - htop
      - tree
      - fzf
      - ripgrep
      - bat
      - curl
      - wget
      - zsh
      - chromium
      - mpv
      - jq
    debian_specific_packages:
      - build-essential
      - firefox-esr
      - lsb-release
      - texlive
      - texlive-science
      - texlive-latex-extra
      - texlive-lang-portuguese
      - texlive-bibtex-extra
      - latexmk
    fedora_specific_packages:
      - qbittorrent
      - firefox
      - discord

- when: ansible_distribution == 'Debian'
  name: Install packages
  become: true
  command: "nala install -y {{ common_packages }} {{ debian_specific_packages }}"


- when: ansible_distribution == 'Fedora'
  name: Fedora packages
  become: true
  dnf:
    names:
      - "{{ common_packages }}"
      - "{{ fedora_specific_packages }}"
    state: latest
