- name: Common packages
  become: true
  package:
    name:
      - xclip
      - htop
      - tree
      - fzf
      - ripgrep
      - bat
      - curl
      - wget
      - zsh
      - chromium
      - mpv
      - jq
    state: present


- name: Debian packages
  become: true
  apt:
    pkg:
      - build-essential
      - thunderbird
      - firefox-esr
      - xz-utils
      - lsb-release
      - texlive
      - texlive-science
      - texlive-latex-extra
      - texlive-lang-portuguese
      - texlive-bibtex-extra
      - latexmk
      - iproute2
  when: ansible_distribution == 'Debian'


- name: Fedora packages
  become: true
  dnf:
    name:
      - qbittorrent
      - xz
      - firefox
      - discord
      - iproute
    state: latest
  when: ansible_distribution == 'Fedora'
