- when: ansible_distribution == 'Debian'
  block:
    - name: Check if vscode is already installed
      command: which code
      ignore_errors: true
      changed_when: false
      register: check_code_installed

    - when: check_code_installed.rc != 0
      block:
        - name: Download vscode .deb
          get_url:
            url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
            dest: /tmp/code.deb

        - name: Install vscode .deb
          become: true
          command: nala install -y /tmp/code.deb

- name: Install extensions
  shell: |
    code \
    --install-extension asvetliakov.vscode-neovim \
    --install-extension TabNine.tabnine-vscode \
    --install-extension rust-lang.rust-analyzer \
    --install-extension jdinhlife.gruvbox \
    --install-extension redhat.ansible \
    --install-extension redhat.vscode-yaml \
    --install-extension ms-python.vscode-pylance \
    --install-extension ms-python.python \
    --install-extension streetsidesoftware.code-spell-checker

- name: Uninstall jupyter extension
  command: code --uninstall-extension ms-toolsai.jupyter
  register: uninstall_jupyter_extension
  failed_when: 'uninstall_jupyter_extension.rc != 0 and "is not installed" not in uninstall_jupyter_extension.stderr'
