- name: Check if omz is already installed
  command: which omz
  failed_when: false
  changed_when: false
  register: check_omz_installed

- when: check_omz_installed.rc != 0
  name: Install oh my zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Stat .zshrc
  stat:
    path: ~/.zshrc
  changed_when: false
  register: stat_zshrc

- when: stat_zshrc.stat.lnk_target != "~/dotfiles/shells/zsh/zshrc.zsh"
  name: Remove default .zshrc
  file:
    path: ~/.zshrc
    state: absent

- name: Link .zshrc
  file:
    src: ~/dotfiles/shells/zsh/zshrc.zsh
    dest: ~/.zshrc
    state: link

- name: Stat .profile
  stat:
    path: ~/.profile
  changed_when: false
  register: stat_profile

- when: stat_profile.stat.lnk_target != "~/dotfiles/shells/profile.sh"
  name: Remove previous .profile
  file:
    path: ~/.profile
    state: absent

- name: Link .profile
  file:
    src: ~/dotfiles/shells/profile.sh
    dest: ~/.profile
    state: link

- name: Use .profile as .zprofile
  file:
    src: ~/.profile
    dest: ~/.zprofile
    state: link

- name: Create themes directory
  file:
    path: ~/.oh-my-zsh/themes
    state: directory

- name: Clone powerlevel10k
  git:
    repo: https://github.com:romkatv/powerlevel10k
    dest: ~/.oh-my-zsh/themes/powerlevel10k

- name: get ZSH_CUSTOM
  set_fact:
    ZSH_CUSTOM_PLUGINS: "{{ lookup('env', 'ZSH_CUSTOM', default='~/.oh-my-zsh/custom') }}/plugins"

- name: Create custom directory
  file:
    path: "{{ ZSH_CUSTOM_PLUGINS }}"
    state: directory

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com:zsh-users/zsh-autosuggestions
    dest: "{{ ZSH_CUSTOM_PLUGINS }}/zsh-autosuggestions"

- name: Clone zsh-syntax-highlighting
  git:
    repo: https://github.com:zsh-users/zsh-syntax-highlighting
    dest: "{{ ZSH_CUSTOM_PLUGINS }}/zsh-syntax-highlighting"
