- name: Install oh my zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  register:  omz_install
  failed_when: 'omz_install.rc != 0 and "The $ZSH folder already exists" not in omz_install.stdout'

- name: Stat .zshrc
  stat:
    path: ~/.zshrc
  changed_when: false
  register: stat_zshrc

- when: not stat_zshrc.stat.islnk or stat_zshrc.stat.lnk_target != "~/dotfiles/shells/zsh/zshrc.zsh"
  name: Remove default .zshrc
  file:
    path: ~/.zshrc
    state: absent

- name: Link .zshrc
  file:
    src: ~/dotfiles/shells/zsh/zshrc.zsh
    dest: ~/.zshrc
    state: link

- name: Stat .profile
  stat:
    path: ~/.profile
  changed_when: false
  register: stat_profile

- when: not stat_profile.stat.islnk or stat_profile.stat.lnk_target != "~/dotfiles/shells/profile.sh"
  name: Remove previous .profile
  file:
    path: ~/.profile
    state: absent

- name: Link .profile
  file:
    src: ~/dotfiles/shells/profile.sh
    dest: ~/.profile
    state: link

- name: Delete shell profile files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/.zprofile
    - ~/.bash_profile

# Use our bashrc in case is necessary
- name: Stat .bashrc
  stat:
    path: ~/.bashrc
  changed_when: false
  register: stat_bashrc

- when: not stat_bashrc.stat.islnk or stat_bashrc.stat.lnk_target != "~/dotfiles/shells/bashrc.sh"
  name: Remove default .bashrc
  file:
    path: ~/.bashrc
    state: absent

- name: Link .bashrc
  file:
    src: ~/dotfiles/shells/bashrc.sh
    dest: ~/.bashrc
    state: link


- name: Create themes directory
  file:
    path: ~/.oh-my-zsh/themes
    state: directory

- name: Clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k
    dest: ~/.oh-my-zsh/themes/powerlevel10k

- name: get ZSH_CUSTOM
  set_fact:
    ZSH_CUSTOM_PLUGINS: "{{ lookup('env', 'ZSH_CUSTOM') or '~/.oh-my-zsh/custom' }}/plugins"

- name: Create custom directory
  file:
    path: "{{ ZSH_CUSTOM_PLUGINS }}"
    state: directory

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ZSH_CUSTOM_PLUGINS }}/zsh-autosuggestions"

- name: Clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: "{{ ZSH_CUSTOM_PLUGINS }}/zsh-syntax-highlighting"
