- hosts: localhost
  tasks:
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/brave.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/prog_langs_version_managers.yml