- hosts: localhost
  tasks:
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/brave.yml
    - include_tasks: tasks/flatpak.yml
    - include_tasks: tasks/alacritty.yml
    - include_tasks: tasks/nerd_fonts.yml
    - include_tasks: tasks/vscode.yml
    - include_tasks: debian_tasks/jetbrains_toolbox.yml
    - include_tasks: debian_tasks/docker.yml
    - include_tasks: debian_tasks/work.yml
    - include_tasks: debian_tasks/i3.yml

    - name: Upgrade all packages
      become: true
      shell: nala update ; nala upgrade -y
