- hosts: localhost
  vars:
    nala_version: v0.12.1
  tasks:
    - name: Check if nala is installed
      shell: nala
      register: nala_output
      failed_when: false

    - when: nala_output.rc != 0
      block:
        - name: Install nala dependencies
          become: true
          ansible.builtin.apt:
            name:
              - python3-apt
              - python3-debian
              - pandoc
              - python3-pip
        
        - name: Clone nala repository
          ansible.builtin.git:
            repo: https://gitlab.com/volian/nala.git
            dest: /tmp/nala
            version: "{{ nala_version }}"
        
        - name: Install nala
          become: true
          ansible.builtin.command: make install
          args:
            chdir: /tmp/nala/
    
    - name: Install kde
      become: true
      ansible.builtin.command: nala install -y kde-standard