export PATH=$PATH:$HOME/bin

# Path to oh-my-zsh installation.
export ZSH="/home/aspedrosa/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="mine"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# My custom folder
ZSH_CUSTOM="$HOME/dotfiles/zsh/custom"

# Plugins
plugins=(gitfast docker extract mvn pip python sudo vi-mode)

source $ZSH/oh-my-zsh.sh

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

autoload -Uz compinit
compinit

setopt appendhistory extendedglob nomatch notify
unsetopt beep

HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export VISUAL=vim
export EDITOR="$VISUAL"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

source ~/dotfiles/bash_aliases.sh

# ls don't ignore '.' when sorting by name
export LC_ALL="C"

cat ~/TODO

ls
