# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to oh-my-zsh installation.
export ZSH="/home/aspedrosa/.oh-my-zsh"

# oh-my-zsh theme
ZSH_THEME="mine"

# oh-my-zsh plugins
PLUGINS=(gitfast docker extract mvn pip python sudo vi-mode)
#extract not perfect
#what vi-mode does ;D

source $ZSH/oh-my-zsh.sh

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# MINE

# Compilation flags
# export ARCHFLAGS="-arch x86_64"
#
# The following lines were added by compinstall
zstyle :compinstall filename '/home/aspedrosa/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

setopt appendhistory extendedglob nomatch notify
unsetopt beep

# My aliases
source ~/dotfiles/bash_aliases.sh

export VISUAL=vim
export EDITOR="$VISUAL"

# ls don't ignore '.' when sorting by name
export LC_ALL="C"

cat ~/TODO

ls
