# Path to oh-my-zsh installation.
export ZSH="/home/aspedrosa/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="mine"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# My custom folder
ZSH_CUSTOM="$HOME/dotfiles/zsh/custom"

# Plugins
plugins=(gitfast docker docker-compose extract mvn pip python sudo vi-mode)

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  virtualenv
  context
  vcs
  dir
  command_execution_time
  status
)

POWERLEVEL9K_OS_ICON_FOREGROUND='106'

POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_ETC_ICON=''

POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)

VIRTUAL_ENV_DISABLE_PROMPT=1

POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_CROSS=true

POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""

POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%B%F{yellow}%K{blue}%} $ %{%b%f%k%F{blue}%} %{%f%}"

POWERLEVEL9K_CONTEXT_TEMPLATE=" %{%n%}  %{`hostname -f`%}"

#POWERLEVEL9K_VI_INSERT_MODE_STRING=''
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode)
POWERLEVEL9K_DISABLE_RPROMPT=true

source $ZSH/oh-my-zsh.sh

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

autoload -Uz compinit
compinit

setopt appendhistory extendedglob nomatch notify HIST_IGNORE_SPACE
unsetopt beep

HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export VISUAL=vim
export EDITOR="$VISUAL"
export TERM=xterm-256color #fixex ssh cmds problems

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

source $HOME/dotfiles/bash_aliases.sh

bindkey '^ ' autosuggest-execute

# ls don't ignore '.' when sorting by name
export LC_ALL="C"

ls
